/drone/mavros:
  mavros_node:
    ros__parameters:
      fcu_url: "/dev/ttyTHS1:921600"
      gcs_url: "udp://@localhost"
      target_system_id: 1
      target_component_id: 1
      fcu_protocol: "v2.0"

  local_position:
    ros__parameters:
      frame_id: "map"
      tf:
        send: false
        frame_id: "map"
        child_frame_id: "base_link"
        send_fcu: false

  odometry:
    ros__parameters:
      fcu:
        odom_parent_id_des: "map"
        odom_child_id_des: "base_link"

  time:
    ros__parameters:
      time_ref_source: "fcu"  # time_reference source
      timesync_mode: MAVLINK
      timesync_avg_alpha: 0.6 # timesync averaging factor

  mavros:
    ros__parameters:
      plugin_allowlist: 
        - altitude
        - command
        - companion_process_status
        - global_position
        - home_position
        - local_position
        - odometry
        - onboard_computer_status
        - param
        - play_tune
        - setpoint_position
        - setpoint_raw
        - sys_status
        - sys_time


/drone/T265:
  camera:
    ros__parameters:
      device_type: "t265"
      # camera_name: "T265"

      enable_fisheye1: false
      enable_fisheye2: false

      tf_publish_rate: 50.0 
      pose_fps: 200 
      pose_enabled: true 
      publish_odom_tf: true 
      publish_tf: true 



# https://github.com/IntelRealSense/realsense-ros/blob/ros2-beta/realsense2_camera/launch/rs_launch.py
/drone/D435:
  camera:
    ros__parameters:
      device_type: "d4."
      camera_name: "D435"


      unite_imu_method: 0
      enable_depth: true
      enable_color: true
      enable_infra1: false
      enable_infra2: false
      infra_rgb: false
      gyro_fps: 0
      accel_fps: 0
      enable_gyro: false
      enable_accel: false
      enable_sync: false
      clip_distance: -2.0
      linear_accel_cov: 0.01
      allow_no_texture_points: false

      align_depth:
        enable: false

      rgb_camera:
        profile: '0,0,0'

      tracking_module:
        profile: '0,0,0'

      colorizer:
        enable: false

      pointcloud:
        enable: false
        stream_filter: 2
        stream_index_filter: 0
        ordered_pc: false

      decimation_filter:
        enable: false

      depth_module:
        profile: '0,0,0'
        exposure:
          1: 7500
          2: 1
        gain:
          1: 16
          2: 16
      