
/drone/mavros:
  mavros_node:
    ros__parameters:
      fcu_url: "/dev/ttyTHS1:921600"
      gcs_url: "udp://@localhost"
      target_system_id: 1
      target_component_id: 1
      fcu_protocol: "v2.0"

  local_position:
    ros__parameters:
      frame_id: "map"
      tf:
        send: false
        frame_id: "map"
        child_frame_id: "base_link"
        send_fcu: false

  odometry:
    ros__parameters:
      fcu:
        odom_parent_id_des: "map"
        odom_child_id_des: "base_link"

  time:
    ros__parameters:
      time_ref_source: "fcu"  # time_reference source
      timesync_mode: MAVLINK
      timesync_avg_alpha: 0.6 # timesync averaging factor

  mavros:
    ros__parameters:
      plugin_allowlist: 
        - altitude
        - command
        - companion_process_status
        - global_position
        - home_position
        - local_position
        - odometry
        - onboard_computer_status
        - param
        - play_tune
        - setpoint_position
        - setpoint_raw
        - sys_status
        - sys_time

        
/drone/realsense:
  camera:
    ros__parameters:
      tf_publish_rate: 20 
      pose_fps: 200 
      pose_enabled: true 
      publish_odom_tf: true 
      publish_tf: true 
