
/drone/mavros:
  mavros_node:
    ros__parameters:
      fcu_url: "udp://:14540@127.0.0.1:14557"
      gcs_url: ""
      target_system_id: 1
      target_component_id: 1
      fcu_protocol: "v2.0"
  
  local_position:
    ros__parameters:
      tf:
        send: True  
